2020-05-06 12:48:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:16 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:21 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 176: headers=self._headers, json=app_details)
2020-05-06 12:48:23 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:48:23 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 221: r = requests.post('https://%s-disp.coolkit.cc:8080/dispatch/app' % self._api_region, headers=self._headers)
2020-05-06 12:48:26 WARNING (MainThread) [homeassistant.components.lovelace] Resources need to be specified in your configuration.yaml. Please see the docs.
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:27 ERROR (MainThread) [homeassistant.components.automation] Entity id already exists - ignoring: automation.tuindeur_is_nog_open. Platform automation does not generate unique IDs
2020-05-06 12:48:28 WARNING (MainThread) [homeassistant.components.mqtt] Data in your configuration entry is going to override your configuration.yaml: {'broker': 'core-mosquitto', 'discovery': True, 'password': 'aupohjidohcoh1ahc0ootudoo2OofeeQu4eVah0nuWeVeinoogah0dei6JuJughi', 'port': 1883, 'protocol': '3.1.1', 'username': 'homeassistant'}
2020-05-06 12:48:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for google_geocode which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for jumbo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-06 12:48:29 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:48:29 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:48:30 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:48:30 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:48:31 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 62: api = JumboApi(username, password)
2020-05-06 12:48:31 WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.
2020-05-06 12:48:31 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 12:48:31 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 12:48:32 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:48:32 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:48:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 12:48:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 12:48:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 12:48:36 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:48:36 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:48:36 ERROR (MainThread) [glances_api] Can not load data from Glances API
2020-05-06 12:48:36 WARNING (MainThread) [homeassistant.config_entries] Config entry for glances not ready yet. Retrying in 5 seconds.
2020-05-06 12:48:36 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-05-06 12:48:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:48:38 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform squeezebox is taking over 10 seconds.
2020-05-06 12:48:38 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds.
2020-05-06 12:48:39 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform nest is taking over 10 seconds.
2020-05-06 12:48:42 WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform google is taking over 10 seconds.
2020-05-06 12:48:44 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:48:44 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:48:44 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle climatisation state for WAUZZZF48GA044048: 403, message='Forbidden', url='https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZF48GA044048/climater
2020-05-06 12:48:44 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle charger state for WAUZZZF48GA044048: 403, message='Forbidden', url='https://msg.volkswagen.de/fs-car/bs/batterycharge/v1/Audi/DE/vehicles/WAUZZZF48GA044048/charger
2020-05-06 12:48:48 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2020-05-06 12:49:00 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:49:00 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:49:01 ERROR (MainThread) [glances_api] Can not load data from Glances API
2020-05-06 12:49:01 WARNING (MainThread) [homeassistant.config_entries] Config entry for glances not ready yet. Retrying in 10 seconds.
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:04 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:06 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:06 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:06 WARNING (MainThread) [homeassistant.helpers.translation] apple_tv: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:06 WARNING (MainThread) [homeassistant.helpers.translation] audiconnect: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-06 12:49:17 WARNING (MainThread) [homeassistant.components.ps4.media_player] PS4 could not be reached
2020-05-06 12:49:24 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:49:32 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:49:32 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:50:25 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:50:37 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:50:37 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:51:26 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:52:27 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:52:37 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:52:37 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:53:28 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:54:29 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:54:37 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:54:37 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:55:30 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:56:31 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:56:38 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:56:38 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:57:29 ERROR (SyncWorker_2) [homeassistant.components.qnap.sensor] Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.0.1.101', port=8080): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 195, in update
    self.data["system_health"] = self._api.get_system_health()
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 121, in get_system_health
    resp = self._get_url("management/manaRequest.cgi?subfunc=sysinfo&sysHealth=1")
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 69, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/qnapstats/qnap_stats.py", line 85, in _execute_get_url
    resp = self._session.get(url, timeout=self._timeout, verify=self._verify_ssl)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.0.1.101', port=8080): Read timed out. (read timeout=5)
2020-05-06 12:57:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:58:33 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 12:58:38 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 12:58:38 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 12:59:34 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:00:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:00:38 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:00:38 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:00:44 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.129: Exception trying to establish web socket connection for hub 12823966: Cannot connect to host 10.0.1.129:8088 ssl:None [Connect call failed ('10.0.1.129', 8088)]
2020-05-06 13:01:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:01:42 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: No dts in packet
2020-05-06 13:01:45 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.129: Connection timed out for hub 12823966
2020-05-06 13:01:49 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.197: Connection timed out for hub 14440977
2020-05-06 13:02:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:02:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:02:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:03:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:04:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:04:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:04:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:04:05 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:04:06 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:04:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:04:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:04:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:05:40 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:06:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:06:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:06:41 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:07:42 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:08:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:08:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:08:43 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:09:44 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:10:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:10:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:10:45 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:11:46 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:12:39 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:12:39 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:12:47 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:13:22 ERROR (MainThread) [aioharmony.hubconnector] 10.0.1.197: Connection timed out for hub 14440977
2020-05-06 13:13:48 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:14:40 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:14:40 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:14:49 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:15:50 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:16:40 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:16:40 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:16:51 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:17:52 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:18:40 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:18:40 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:18:53 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:19:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:19:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:19:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:19:33 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:19:34 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jumbo doing I/O at custom_components/jumbo/sensor.py, line 98: self.basket = self._api.get_basket()
2020-05-06 13:19:54 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:20:41 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:20:41 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:20:55 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:21:39 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:21:50 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:21:56 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:22:01 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:12 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:23 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:34 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:41 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:22:41 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:22:45 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:56 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:22:57 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:23:07 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:23:18 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:23:21 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 13:23:29 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:23:40 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:23:51 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:23:58 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:24:02 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:13 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:24 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:34 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:41 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:24:41 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:24:45 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:56 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:24:59 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:25:07 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:25:18 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:25:29 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:25:39 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:25:50 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:00 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:26:01 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:12 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:22 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:33 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:42 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:26:42 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:26:44 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:26:55 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:27:01 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:27:06 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:27:14 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 13:27:17 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:27:28 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:27:39 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:27:50 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:01 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:28:12 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:23 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:34 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:42 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:28:42 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:28:45 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:28:56 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:29:03 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:29:07 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:29:10 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 13:29:18 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:29:29 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:29:40 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ServerDisconnectedError'>
2020-05-06 13:30:04 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:30:08 ERROR (MainThread) [frontend.js.latest.202004272] https://casatinus.duckdns.org/local/community/bar-card/bar-card.js:5335:1 Uncaught SyntaxError: Unexpected token 'export'
2020-05-06 13:30:42 ERROR (Thread-6) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2020-05-06 13:30:42 WARNING (Thread-6) [homeassistant.components.mqtt] Disconnected from MQTT (5).
2020-05-06 13:31:05 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
2020-05-06 13:32:06 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 374: ), headers=self._headers)
